[build]
    command = "rm -rf out && yarn run build"
    publish = "out"
    functions = "my_functions"

# Skip the Next.js plugin for static exports
[build.environment]
    NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Note: @netlify/plugin-nextjs is disabled for static exports
# If enabled in Netlify UI, it must be manually disabled there
# to prevent duplicate execution conflicts

[[plugins]]
  package = "netlify-plugin-image-optim"
[[plugins]]
  package = "netlify-plugin-inline-source"
[[plugins]]
  package = "@netlify/plugin-sitemap"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/home"
    to = "/"
[[redirects]]
    from = "/github"
    to = "https://github.com/ajayliu/"
[[redirects]]
    from = "/linkedin"
    to = "https://www.linkedin.com/in/ajayliu/"
[[redirects]]
    from = "/googleplay"
    to = "https://play.google.com/store/apps/dev?id=6962993996464856524"
[[redirects]]
    from = "/donate"
    to = "https://www.buymeacoffee.com/ajayliu/"
[[redirects]]
    from = "/youtube"
    to = "https://www.youtube.com/watch?v=I2y8RWBl9Do"
    

[[redirects]]
    from = "/sheep-goat"
    to = "https://sheep-goat.ajayliu.com/"
[[redirects]]
    from = "/sheep-or-goat"
    to = "https://sheep-goat.ajayliu.com/"
[[redirects]]
    from = "/inspiration-jar"
    to = "https://inspiration-jar.ajayliu.com/"
[[redirects]]
    from = "/inspiration"
    to = "https://inspiration-jar.ajayliu.com/"
[[redirects]]
    from = "/10seconds"
    to = "https://10seconds.ajayliu.com/"
[[redirects]]
    from = "/ichiban"
    to = "https://ichiban.ajayliu.com/"
[[redirects]]
    from = "/when"
    to = "https://when.ajayliu.com/"
[[redirects]]
    from = "/blog"
    to = "https://blog.ajayliu.com/"
[[redirects]]
    from = "/acq"
    to = "https://anime-character-quiz.ajayliu.com/"
[[redirects]]
    from = "/anime-character-quiz"
    to = "https://anime-character-quiz.ajayliu.com/"
[[redirects]]
    from = "/bet-you-dont-know"
    to = "https://bet-you-dont-know.ajayliu.com/"
[[redirects]]
    from = "/bet"
    to = "https://bet-you-dont-know.ajayliu.com/"
[[redirects]]
    from = "/notation"
    to = "http://notation-visualizer.ajayliu.com/"

[[redirects]]
    from = "/cubeinc"
    to = "/games/cubeinc"
[[redirects]]
    from = "/cashout"
    to = "/games/cashout"
[[redirects]]
    from = "/pixelbeats"
    to = "/games/pixelbeats"
[[redirects]]
    from = "/colorjump"
    to = "/games/colorjump"
[[redirects]]
    from = "/bouncearchitect"
    to = "/games/bouncearchitect"
[[redirects]]
    from = "/tapdefender"
    to = "/games/tapdefender"
[[redirects]]
    from = "/triviadash"
    to = "/games/triviadash"

[[redirects]]
    from = "/allen"
    to = "/cards/allen"
[[redirects]]
    from = "/tiffany"
    to = "/cards/tiffany"
[[redirects]]
    from = "/ron"
    to = "/cards/ron"
[[redirects]]
    from = "/daniel"
    to = "/cards/daniel"
[[redirects]]
    from = "/talha"
    to = "/cards/talha"
[[redirects]]
    from = "/allmale"
    to = "https://drive.google.com/drive/folders/1w6r2isw6Oc4BQPwCj8S_SxxYq0lxJs8h?usp=sharing"
[[redirects]]
    from = "/angie"
    to = "/cards/angie"
[[redirects]]
    from = "/appfolio"
    to = "/cards/appfolio"

[[redirects]]
    from = "/resume"
    to = "/resume.pdf"